# Generated by Django 2.1.7 on 2019-03-31 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190331_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 7, 34, 18, 764921, tzinfo=utc)),
        ),
    ]
