# Generated by Django 2.1.7 on 2019-03-31 08:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190331_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 31, 8, 21, 54, 820659, tzinfo=utc)),
        ),
    ]
