# Generated by Django 2.1.7 on 2019-03-31 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190331_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='autror',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
